"""Initial migration - create all tables

Revision ID: 17360e17a097
Revises: 
Create Date: 2024-04-19 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17360e17a097'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('plan', sa.String(), nullable=True),
        sa.Column('daily_limit', sa.Integer(), nullable=True),
        sa.Column('daily_used', sa.Integer(), nullable=True),
        sa.Column('api_key', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_key'), 'users', ['api_key'], unique=True)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_plan'), 'users', ['plan'], unique=False)
    
    # Create meme_templates table
    op.create_table('meme_templates',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('alternative_names', sa.JSON(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('font_path', sa.String(), nullable=False),
        sa.Column('text_color', sa.String(), nullable=False),
        sa.Column('text_stroke', sa.Boolean(), nullable=True),
        sa.Column('usage_instructions', sa.Text(), nullable=False),
        sa.Column('number_of_text_fields', sa.Integer(), nullable=False),
        sa.Column('text_coordinates_xy_wh', sa.JSON(), nullable=False),
        sa.Column('example_output', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meme_templates_name'), 'meme_templates', ['name'], unique=True)
    
    # Create memes table
    op.create_table('memes',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column('template_name', sa.String(), nullable=False),
        sa.Column('template_id', sa.Integer(), nullable=False),
        sa.Column('meme_text', sa.JSON(), nullable=False),
        sa.Column('image_url', sa.String(), nullable=False),
        sa.Column('thumbnail_url', sa.String(), nullable=True),
        sa.Column('share_count', sa.Integer(), nullable=True),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memes_public_created', 'memes', ['is_public', 'created_at'], unique=False)
    op.create_index('ix_memes_template_created', 'memes', ['template_name', 'created_at'], unique=False)
    op.create_index('ix_memes_user_created', 'memes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_memes_created_at'), 'memes', ['created_at'], unique=False)
    op.create_index(op.f('ix_memes_is_public'), 'memes', ['is_public'], unique=False)
    op.create_index(op.f('ix_memes_share_count'), 'memes', ['share_count'], unique=False)
    op.create_index(op.f('ix_memes_template_id'), 'memes', ['template_id'], unique=False)
    op.create_index(op.f('ix_memes_template_name'), 'memes', ['template_name'], unique=False)
    op.create_index(op.f('ix_memes_user_id'), 'memes', ['user_id'], unique=False)
    
    # Create meme_jobs table
    op.create_table('meme_jobs',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=True),
        sa.Column('prompt', sa.Text(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('result_meme_ids', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_created', 'meme_jobs', ['status', 'created_at'], unique=False)
    op.create_index('ix_jobs_user_status', 'meme_jobs', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_meme_jobs_created_at'), 'meme_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_meme_jobs_status'), 'meme_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_meme_jobs_user_id'), 'meme_jobs', ['user_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop meme_jobs table
    op.drop_index(op.f('ix_meme_jobs_user_id'), table_name='meme_jobs')
    op.drop_index(op.f('ix_meme_jobs_status'), table_name='meme_jobs')
    op.drop_index(op.f('ix_meme_jobs_created_at'), table_name='meme_jobs')
    op.drop_index('ix_jobs_user_status', table_name='meme_jobs')
    op.drop_index('ix_jobs_status_created', table_name='meme_jobs')
    op.drop_table('meme_jobs')
    
    # Drop memes table
    op.drop_index(op.f('ix_memes_user_id'), table_name='memes')
    op.drop_index(op.f('ix_memes_template_name'), table_name='memes')
    op.drop_index(op.f('ix_memes_template_id'), table_name='memes')
    op.drop_index(op.f('ix_memes_share_count'), table_name='memes')
    op.drop_index(op.f('ix_memes_is_public'), table_name='memes')
    op.drop_index(op.f('ix_memes_created_at'), table_name='memes')
    op.drop_index('ix_memes_user_created', table_name='memes')
    op.drop_index('ix_memes_template_created', table_name='memes')
    op.drop_index('ix_memes_public_created', table_name='memes')
    op.drop_table('memes')
    
    # Drop meme_templates table
    op.drop_index(op.f('ix_meme_templates_name'), table_name='meme_templates')
    op.drop_table('meme_templates')
    
    # Drop users table
    op.drop_index(op.f('ix_users_plan'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_api_key'), table_name='users')
    op.drop_table('users')
    
    # ### end Alembic commands ###