"""Add missing columns

Revision ID: 56acdf9f25ae
Revises: 20260424_phase1
Create Date: 2026-04-26 12:07:08.917222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56acdf9f25ae'
down_revision = '20260424_phase1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meme_templates', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('memes', sa.Column('like_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_memes_like_count'), 'memes', ['like_count'], unique=False)
    op.add_column('users', sa.Column('preferences', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_index(op.f('ix_memes_like_count'), table_name='memes')
    op.drop_column('memes', 'like_count')
    op.drop_column('meme_templates', 'image_url')
    # ### end Alembic commands ###